[package]
name = "gb_int"
version = "0.1.0"
authors = ["Blake Loring <blake@parsed.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
